### ISSUE TITLE
An example on how one can use this toolkit

### ISSUE THREAD

**Issue by MuhammadPen** [readium/ts-toolkit#16]
It would be helpful if there is a simple code example on using this toolkit. As a new comer to readium and someone who just wants to add readium to his react app, this is quite confusing.

**Comment by HadrienGardeur** [comment]
Hello @MuhammadPen,

Readium Web is still in its infancy and will eventually contain a test app and full documentation but for now the team is mostly focused on building various navigators (see https://readium.org/architecture):

- the one for EPUB reflow is in active development (see the list of PR)
- PDF is next, with work planned in October/November
- and EPUB FXL is planned for early next year

If you'd like to contribute and help us build the project, we recommend joining our bi-monthly calls, that's the best way to get introduced to the team and project.
If you're interested in simply using Readium Web to build a Web Reader, you'll have to bear with us right now as this is not ready for primetime yet.


There are other options that you can look into in the meantime:

- if you're looking to build a React app for desktop/laptops using Electron, you can take a look at Readium Desktop
- if you're looking to build a React native app for mobile, we recommend using Readium Mobile
