### ISSUE TITLE
Monorepo Yarn, vs. PNPM, vs. vanilla NPM + Lerna?

### ISSUE THREAD

**Issue by danielweck** [readium/ts-toolkit#2]
* https://classic.yarnpkg.com/en/docs/workspaces/
* https://pnpm.js.org/en/workspaces
* https://lerna.js.org/

This choice will impact the CI Continous Integration setup, lockfiles, there will be differences in terms of flat vs. deep package dependencies (filesystem NPM registry cache), different filesystem locations depending on CLI package management tool (sometimes this knowledge is needed to implement unorthodox build scripts / patches), etc.

**Comment by chocolatkey** [comment]
@danielweck a couple years late, but I settled on PNPM workspaces
