### ISSUE TITLE
Some tools have issues with unicode property escapes in regex

### ISSUE THREAD

**Issue by JayPanoz** [readium/ts-toolkit#49]
It seems that the following:

https://github.com/readium/ts-toolkit/blob/711740799f670e661bad29e0fe023488c2e4477e/shared/src/util/tokenizer/TextTokenizer.ts#L119-L124

Specifically,

```
/[\p{L}\p{N}]+/u
```

make tools such as babel throw an error: 

```sh
Unknown property: L at matchProperty
```

[Could find something similar for RI and Emoji](https://stackoverflow.com/questions/73457529/unicode-property-escapes-in-regex-cause-errors-in-babel), with babel + NextJS involved.

**Comment by chocolatkey** [comment]
@JayPanoz I actually had this uncommitted and ready to push in the `guided-navigation` branch, because I encountered it as well trying to integrate with the Next.JS playground. Here's the fix:
```ts
const trimmedMatcher = new RegExp("[\\p{L}\\p{N}]+", "u");

// Unicode-aware of checking if there's anything that can be spoken in a string
// "Spoken" in this case means at least one unicode letter or unicode number character
export const speakableToken = (token: string): string | null => {
    const trimmedToken = token.trimEnd();
    if(trimmedToken.length === 0) return null;
    if(trimmedToken.match(trimmedMatcher) === null) return null;
    return trimmedToken;
}
```

Feel free to add it

**Comment by JayPanoz** [comment]
@chocolatkey Great thanks. Will integrate in the `vite-build` then, and resolve the issue from the commit.
