### ISSUE TITLE
epub fixed layout zoom on desktop

### ISSUE THREAD

**Issue by patprache** [readium/ts-toolkit#50]
Hello,

I'm starting to look at Readium web to make a fixed layout epub reader: in the testapp reader I can see that pinch is managed on mobile to zoom but I can't find a function to be able to zoom in a desktop context on the press of a button.

Am I missing something?

Thanks !

**Comment by chocolatkey** [comment]
@patprache Thanks for beta-testing things, that's the kind of setting we should probably add an easy function for in the future in the preferences API we plan to implement.
Right now, however, you can use for example `navigator.pool.peripherals.scale = 0.75`, although the API is not guaranteed to remain stable

**Comment by patprache** [comment]
@chocolatkey thank you for your quick reply. 

For the moment I've just added a zoom function in FXLPeripherals.ts

`
 public zoom(scale:number){
        this.scale = scale;
        this.manager.updateBookStyle();
    }
`

It does the job ;)
