### ISSUE TITLE
`Element.tagName` is lower case with `application/xml+xhtml` (upper case with `text/html`)

### ISSUE THREAD

**Issue by danielweck** [readium/ts-toolkit#78]
`isReplacedLikeElement()`:

https://github.com/readium/ts-toolkit/blob/1b268b261a7488078949b9bef335c7a3514d6851/navigator-html-injectables/src/helpers/locator.ts#L4-L6

PR: https://github.com/readium/ts-toolkit/pull/77/files

**Comment by chocolatkey** [comment]
@danielweck thanks for catching that, I totally forgot about that edge case
